version: "3.9"
services:
  hive-metastore:
    image: "hive-metastore/metastore"
    build: .
    command: sh -c "sh /opt/hive-metastore/bin/entrypoint.sh 2>&1 /var/log/metastore.log "
    depends_on:
      - db
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "9083:9083/tcp"
    networks:
      vpc123:
        ipv4_address: 10.5.0.5
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive_metastore
    ports:
      - "3308:3306/tcp"
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      vpc123:
        ipv4_address: 10.5.0.6

volumes:
   db:

networks:
  vpc123:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
