version: "3.8"

services:
  database:
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: metastore
      POSTGRES_DB: metastore_db
    volumes:
      - db:/var/lib/postgresql/data/

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add warehouse http://minio:9000 accesskey secretkey) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb warehouse/local-warehouse;
      exit 0;
      "

  metastore:
    build: .
    image: hive-metastore-standalone:latest
    ports:
      - 9083:9083
    depends_on:
      - database

volumes:
  minio_data:
  db:
